# Numpy

In [1]:
import numpy as np
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
print(arr1.shape)
print(arr1.dtype)
print(arr1.ndim)

(3,)
float64
1


In [22]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8], [9,10,11,12]]
arr2 = np.array(data2)
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)
int32


In [24]:
data3 = np.zeros(10)
data4 = np.ones(10)
data5 = np.empty([2,2])
print(data3)
print(data4)
print(data5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]]


In [26]:
data6 = np.arange(15)
print(data6)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [27]:
data7 = np.eye(5)
print(data7)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2.dtype)

float64
int32


In [31]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [32]:
arr2 = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr2)
arr2.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

In [33]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Operações entre Arrays e Escalares

In [34]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Multiplicação: \n',arr3 * arr3)
print('Subtração: \n',arr3 - arr3)

[[1. 2. 3.]
 [4. 5. 6.]]
Multiplicação: 
 [[ 1.  4.  9.]
 [16. 25. 36.]]
Subtração: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [12]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr3)
print('Escalar dividindo array: \n',1/arr3)
print('Raiz quadrada: \n',arr3 ** 0.5)

[[1. 2. 3.]
 [4. 5. 6.]]
Escalar dividindo array: 
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
Raiz quadrada: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


## Indexação e Broadcast

In [35]:
import numpy as np
arr = np.arange(10)
print(arr)
print(arr[5]) 
print(arr[5:8])
arr[5:8] = 12 #atribuição
print(arr)

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]


In [14]:
arr_slice = arr[5:8]
print(arr_slice)
arr_slice[1] = 12345
print(arr_slice)
print(arr)

[12 12 12]
[   12 12345    12]
[    0     1     2     3     4    12 12345    12     8     9]


In [15]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print(arr2d[0][2]) #igual a print(arr2d[0, 2])

[7 8 9]
3


In [16]:
print(arr2d[:2, 1:])
print(arr2d[1, :2])
print(arr2d[:, :1])

[[2 3]
 [5 6]]
[4 5]
[[1]
 [4]
 [7]]


In [17]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


## Funções Trigonométricas

In [18]:
arr = np.arange(10)
print(arr)
np.sqrt(arr) #raiz quadrada
np.exp(arr) #e^x

[0 1 2 3 4 5 6 7 8 9]


array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [39]:
array = np.rint(np.array([1.5, 1.2, 1.3])) ** 2

array

array([4., 1., 1.])

## Processamento de Dados Usando Arrays

In [40]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [41]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [43]:
result = np.where(cond, xarr, yarr)
result

ValueError: either both or neither of x and y should be given

In [ ]:
arr = np.random.randn(4, 4)
print(arr)
print(np.where(arr > 0, 2, -2)) # atribui 2 p/ x>0, -2 caso contrário
print(np.where(arr > 0, 2, arr)) # atribui 2 p/ x>0, mantém original caso contrário

In [44]:
arr = np.random.randn(5, 4)
print(arr)
print(arr.mean()) #ou np.mean(arr)
print(arr.sum())
print(arr.mean(axis=1))
print(arr.sum(0))

[[ 0.04054796 -0.04816962  0.75977479 -0.70125368]
 [-1.26543292  0.80013907 -0.68451441  0.23950733]
 [-0.03678387 -0.67986072  1.22386934  0.73607019]
 [-0.40104044  1.4122249  -0.35599646 -0.36278444]
 [ 0.6379073  -3.21345031 -0.70573378 -0.09122619]]
-0.13481029863865202
-2.6962059727730403
[ 0.01272486 -0.22757523  0.31082373  0.07310089 -0.84312575]
[-1.02480197 -1.72911669  0.23739947 -0.17968678]


## Outros Métodos

In [45]:
bools = np.array([False, False, True, False])
print(bools.any()) # se houver pelo menos um True
print(bools.all()) # se todos forem True

True
False


In [46]:
arr = np.random.randn(8)
print(arr)
arr.sort() #in-place
print(arr)

[-0.87325928  0.49875166  0.08546043 -0.10902365  1.1613042  -1.94462745
  0.4847142  -0.00221922]
[-1.94462745 -0.87325928 -0.10902365 -0.00221922  0.08546043  0.4847142
  0.49875166  1.1613042 ]


In [49]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.unique(names))
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
print(np.unique(ints))

['Bob' 'Joe' 'Will']
[1 2 3 4]


In [51]:
values = np.array([6, 0, 0, 3, 2, 5, 6])
np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

## Álgebra Linear

In [52]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(x)
print(y)
z = x.dot(y) #igual aa np.dot(x,y)
print(z)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
[[ 28.  64.]
 [ 67. 181.]]


In [53]:
from numpy.linalg import inv
X = np.random.randn(5, 5)
print(X)
mat = X.T.dot(X) #transposta * X
print(mat)
print(inv(mat)) #inversa

[[ 1.16058712 -0.70212933 -0.11714315  1.43539041 -0.91149534]
 [ 0.82703842 -1.03091429  0.21671911  0.78242191  2.03362201]
 [-0.57386543  0.42736099 -2.1228283   0.08624197  1.09012002]
 [ 0.78496527 -0.32860484  0.17024377 -0.12265905  1.01521417]
 [ 1.96090333  1.15354704  0.55217994 -1.37805883  1.43438538]]
[[ 6.82158889  0.09131517  2.4779049  -0.5350259   3.60803054]
 [ 0.09131517  3.17705921 -0.46736058 -3.32693251  0.33039911]
 [ 2.4779049  -0.46736058  4.90097532 -0.96347565 -0.80176472]
 [-0.5350259  -3.32693251 -0.96347565  4.59405873 -1.72437978]
 [ 3.60803054  0.33039911 -0.80176472 -1.72437978  9.24292513]]
[[ 0.8673305  -2.48712945 -1.24601186 -2.25352524 -0.7781683 ]
 [-2.48712945 10.42626542  4.50831519  9.22354821  2.70999906]
 [-1.24601186  4.50831519  2.27576584  4.07880191  1.28359125]
 [-2.25352524  9.22354821  4.07880191  8.41894389  2.47443657]
 [-0.7781683   2.70999906  1.28359125  2.47443657  0.88806089]]


## Geração de Números Aleatórios

In [54]:
samples = np.random.normal(size=(4, 4))
samples

array([[-0.82861604, -1.06320319, -0.82395656, -0.67366292],
       [ 0.68445131, -0.03211237, -0.52751821,  0.43271015],
       [-0.1964578 , -1.59428238,  0.58639989, -1.14397327],
       [ 1.16990356,  1.37988509, -0.73972654,  1.29939757]])