# Desafio 1

In [163]:
import numpy as np
import unittest

In [164]:
class Matematica():
    class Trigonometrica:
        def seno(self, array):
            return np.sin(array)
        
        def cosseno(self, array):
            return np.cos(array)
        
    class Algebrica:
        def soma(self, array1, array2):
            return np.add(array1, array2)
        
        def subtracao(self, array1, array2):
            return np.subtract(array1, array2)
        
        def divisao(self, array1, array2):
            return np.divide(array1, array2)
        
        def multiplicacao(self, array1, array2):
            return np.multiply(array1, array2)
        

### Testes

In [168]:
class AlgebricaTestes(unittest.TestCase):
    def setUp(self):
        self.algebrica = Matematica.Algebrica()    
    
    def test_deve_somar_dois_arrays(self):
        array1 = np.array([1,2,3,4])
        array2 = np.array([1,2,3,4])
        
        resultado = self.algebrica.soma(array1, array2)
        np.testing.assert_array_equal(resultado, np.array([2,4,6,8]))
        
    def test_deve_subtrair_dois_arrays(self):
        array1 = np.array([1,2,3,4])
        array2 = np.array([1,2,3,4])
        
        resultado = self.algebrica.subtracao(array1, array2)
        np.testing.assert_array_equal(resultado, np.array([0,0,0,0]))
        
    def test_deve_dividir_dois_arrays(self):
        array1 = np.array([1,2,3,4])
        array2 = np.array([1,2,3,4])
        
        resultado = self.algebrica.divisao(array1, array2)
        np.testing.assert_array_equal(resultado, np.array([1,1,1,1]))
        
    def test_deve_multiplicar_dois_arrays(self):
        array1 = np.array([1,2,3,4])
        array2 = np.array([1,2,3,4])
        
        resultado = self.algebrica.multiplicacao(array1, array2)
        np.testing.assert_array_equal(resultado, np.array([1,4,9,16]))

In [169]:
class TrigonometriaTestes(unittest.TestCase):
    def setUp(self):
        self.trigonometria = Matematica.Trigonometrica()  
        
    def test_deve_obter_cosseno(self):
        array = np.array([1,2,3,4])
        
        resultado = self.trigonometria.cosseno(array)
        np.allclose(resultado, np.array([0.540302,-0.416147,-0.989992,-0.653644]))
    
    def test_deve_obter_seno(self):
        array = np.array([1,2,3,4])
        
        resultado = self.trigonometria.seno(array)
        np.allclose(resultado, np.array([0.841471,0.909297,0.14112,-0.756802]))

In [170]:
if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

.......
----------------------------------------------------------------------
Ran 7 tests in 0.010s

OK


# Desafio 2

In [175]:
numeros = np.random.normal(size=(4,4))

print('Desvio padrão:', np.std(numeros))
print('Mínimo:', np.min(numeros))
print('Máximo:', np.max(numeros))
print('Variancia:', np.var(numeros))
print('Média:', np.mean(numeros))
print('Soma:', np.sum(numeros))

Desvio padrão: 1.14335559519345
Mínimo: -2.7353013111825417
Máximo: 1.6000821204334275
Variancia: 1.3072620170601683
Média: -0.24113660961007158
Soma: -3.8581857537611453


# Desafio 3

In [182]:
a = np.array(np.arange(10))
b = np.arange(11, 21)
calculadora = Matematica.Algebrica()


print('Soma:', calculadora.soma(a,b))
print('Subtracao:', calculadora.subtracao(a,b))
print('Divisão:', calculadora.divisao(a,b))
print('Multiplicação:', calculadora.multiplicacao(a,b))

Soma: [11 13 15 17 19 21 23 25 27 29]
Subtracao: [-11 -11 -11 -11 -11 -11 -11 -11 -11 -11]
Divisão: [0.         0.08333333 0.15384615 0.21428571 0.26666667 0.3125
 0.35294118 0.38888889 0.42105263 0.45      ]
Multiplicação: [  0  12  26  42  60  80 102 126 152 180]


# Desafio 4

In [188]:
from numpy.linalg import inv
X = np.random.randn(5, 5)

mat = X.T.dot(X)

print(inv(mat))

[[ 1.24666846  0.01378296  0.19400326  0.1427908  -0.00147026]
 [ 0.01378296  0.34066355 -0.15885114  0.04161304 -0.05433395]
 [ 0.19400326 -0.15885114  0.27933524  0.04333592  0.03077853]
 [ 0.1427908   0.04161304  0.04333592  0.18873808  0.05949029]
 [-0.00147026 -0.05433395  0.03077853  0.05949029  0.25565834]]


# Desafio 5

In [216]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

def remover_elementos_nao_correspondentes(arrayA, arrayB):
    return np.setdiff1d(arrayA,arrayB)
    
remover_elementos_nao_correspondentes(a, b)

array([1, 2, 3, 4])

# Desafio 6

In [239]:
def vai(array, n, m):
    um = np.where(array > n)
    return np.where(um < m)

vai(np.array([1,4,6,8,12,15]), 3, 13)

array([-1,  4,  6,  8, 12,  0])